repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
          exclude: \.min\.css$|\.po$
        - id: mixed-line-ending
          args: [ '--fix=lf' ]
