# Generated by Django 2.2.16 on 2020-09-16 18:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("fleetpings", "0005_fleettype_restricted_to_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetdoctrine",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict this doctrine to the following group(s) ...",
                related_name="fleetdoctrine_require_groups",
                to="auth.Group",
            ),
        ),
    ]
