# Generated by Django 4.0.10 on 2023-05-11 14:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleetpings", "0010_use_ellipsis_character_in_strings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_default_fleet_types",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether to use default fleet types. If checked, the default fleet types (Roaming, Home Defense, StratOP, and CTA) will be added to the Fleet Type dropdown.",
                    ),
                ),
                (
                    "use_default_ping_targets",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether to use default ping targets. If checked, the default ping targets (@everyone and @here) will be added to the Ping Target dropdown.",
                    ),
                ),
                (
                    "use_doctrines_from_fittings_module",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether to use the doctrines from the Fittings modules in the doctrine dropdown. Note: The fittings module needs to be installed for this.",
                    ),
                ),
                (
                    "webhook_verification",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether to verify Webhooks URLs or not. Note: When unchecked Webhook URLs will not be verified, so the app can be used with non-Discord Webhooks as well. This is up to you, not every Webhook might understand what this app is sending.",
                    ),
                ),
            ],
            options={
                "verbose_name": "setting",
                "verbose_name_plural": "settings",
                "default_permissions": (),
            },
        ),
    ]
