# Generated by Django 5.2.16 on 2026-07-09 08:59

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleetpings", "0015_alter_discordpingtarget_options_and_more"),
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordpingtarget",
            name="name",
            field=models.OneToOneField(
                help_text="Name of the Discord role to ping. (Note: This must be an Auth group that is synced to Discord.)",
                on_delete=django.db.models.deletion.CASCADE,
                to="groupmanagement.group",
                verbose_name="Group name",
            ),
        ),
        migrations.AlterField(
            model_name="discordpingtarget",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict ping rights to the following groups…",
                related_name="discord_role_require_groups",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="fleetdoctrine",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict this doctrine to the following groups…",
                related_name="fleetdoctrine_require_groups",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="fleettype",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict this fleet type to the following groups…",
                related_name="+",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict ping rights to the following groups…",
                related_name="webhook_require_groups",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
    ]
