name: pre-commit

on:
  push:
    branches:
      - '**'

    tags-ignore:
      - v*

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
#      with:
#        python-version: 3.6
    - uses: pre-commit/action@v2.0.0
